# Generated by Django 5.0 on 2025-01-23 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chitiethoadon',
            fields=[
                ('chitiethoadonid', models.IntegerField(db_column='ChiTietHoaDonID', primary_key=True, serialize=False)),
                ('soluong', models.IntegerField(db_column='SoLuong')),
                ('giatien', models.DecimalField(db_column='GiaTien', decimal_places=2, max_digits=10)),
                ('tongtien', models.DecimalField(blank=True, db_column='TongTien', decimal_places=2, max_digits=21, null=True)),
            ],
            options={
                'db_table': 'ChiTietHoaDon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hoadon',
            fields=[
                ('hoadonid', models.IntegerField(db_column='HoaDonID', primary_key=True, serialize=False)),
                ('total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=10)),
                ('phuongthucthanhtoan', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PhuongThucThanhToan', max_length=255)),
                ('thoigian', models.DateTimeField(blank=True, db_column='ThoiGian', null=True)),
                ('trangthai', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TrangThai', max_length=255)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'HoaDon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Khachhang',
            fields=[
                ('khachhangid', models.IntegerField(db_column='KhachHangID', primary_key=True, serialize=False)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=255, unique=True)),
                ('hoten', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='HoTen', max_length=255, null=True)),
                ('sdt', models.IntegerField(blank=True, db_column='SDT', null=True)),
                ('diachi', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DiaChi', max_length=255, null=True)),
            ],
            options={
                'db_table': 'KhachHang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleid', models.IntegerField(db_column='RoleID', primary_key=True, serialize=False)),
                ('rolename', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='RoleName', max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'Role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sanpham',
            fields=[
                ('sanphamid', models.IntegerField(db_column='SanPhamID', primary_key=True, serialize=False)),
                ('tensp', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TenSP', max_length=255, unique=True)),
                ('giatien', models.FloatField(db_column='GiaTien', unique=True)),
                ('soluong', models.IntegerField(db_column='SoLuong', unique=True)),
                ('thoigiannhaphang', models.DateField(blank=True, db_column='ThoiGianNhapHang', null=True)),
                ('trangthai', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TrangThai', max_length=255)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=255, null=True)),
                ('imageurl', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ImageUrl', max_length=255, null=True)),
            ],
            options={
                'db_table': 'SanPham',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Registeruser',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.CreateModel(
            name='Taikhoan',
            fields=[
                ('taikhoanid', models.OneToOneField(db_column='TaiKhoanID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.khachhang')),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UserName', max_length=255, unique=True)),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PassWord', max_length=255)),
            ],
            options={
                'db_table': 'TaiKhoan',
                'managed': False,
            },
        ),
    ]
